begin
  foo
rescue Error => x
end
